# Generated by Django 4.0.4 on 2022-06-07 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('idFoto', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreFoto', models.CharField(max_length=100)),
                ('nombreArchivo', models.CharField(max_length=256)),
                ('descripcion', models.CharField(max_length=500)),
            ],
        ),
    ]
