# Generated by Django 4.0.4 on 2022-06-11 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Foto',
        ),
    ]
