# Generated by Django 4.0.4 on 2022-06-11 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='nombre',
        ),
        migrations.AddField(
            model_name='usuario',
            name='dir_entrega',
            field=models.CharField(default='default_value', max_length=40),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nombre_usuario',
            field=models.CharField(default='default_value', max_length=30),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(default='default_value', max_length=15),
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_pedido', models.DateField()),
                ('total', models.IntegerField()),
                ('estado', models.CharField(max_length=15)),
                ('id_productos', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='back.producto')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='back.usuario')),
            ],
        ),
    ]
