# Generated by Django 4.0.4 on 2022-06-11 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0002_producto_remove_usuario_nombre_usuario_dir_entrega_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='dir_entrega',
        ),
    ]
