# Generated by Django 4.0.4 on 2022-06-12 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0003_remove_usuario_dir_entrega'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='nombre_usuario',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='id_usuario',
        ),
    ]
