# Generated by Django 4.0.4 on 2022-07-04 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0004_rename_nombre_usuario_usuario_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria_producto',
            field=models.CharField(default='default_value', max_length=50),
        ),
    ]
