# Generated by Django 4.0.4 on 2022-07-05 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0005_producto_categoria_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='nombreFoto',
            field=models.CharField(default='default_value', max_length=256),
        ),
    ]
