# Generated by Django 4.0.4 on 2022-07-05 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0006_producto_nombrefoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='id_producto',
        ),
        migrations.AddField(
            model_name='producto',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=150),
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
    ]
