# Generated by Django 4.0.4 on 2022-07-08 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0007_remove_producto_id_producto_producto_id_usuario_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='descripcion',
            new_name='descripcion_producto',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='nombreFoto',
            new_name='nombre_foto',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='precio',
            new_name='precio_producto',
        ),
        migrations.AddField(
            model_name='producto',
            name='id_producto',
            field=models.CharField(default='1', max_length=50),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock_producto',
            field=models.IntegerField(default='1'),
        ),
    ]
