# Generated by Django 4.0.4 on 2022-07-09 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0010_categoria_remove_producto_categoria_producto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='nombre_foto',
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(default='Sin_imagen', upload_to=''),
        ),
    ]
