# Generated by Django 4.1.4 on 2023-02-25 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0013_admin_categoria1_cliente_cupon_personal_tienda_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='admin',
            new_name='administrador',
        ),
    ]
