# Generated by Django 4.1.4 on 2023-02-25 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0016_alter_categoria1_options_alter_producto1_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cli_apellido',
            field=models.CharField(default='Apellido cliente', max_length=30, verbose_name='Apellido cliente'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cli_nombre',
            field=models.CharField(default='Nombre cliente', max_length=30, verbose_name='Nombre cliente'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cli_password',
            field=models.CharField(default='Password cliente', max_length=32, verbose_name='Contraseña'),
        ),
        migrations.AlterField(
            model_name='personal_tienda',
            name='per_apellido',
            field=models.CharField(default='Apellido empleado', max_length=30, verbose_name='Apellido cliente'),
        ),
        migrations.AlterField(
            model_name='personal_tienda',
            name='per_nombre',
            field=models.CharField(default='Nombre empleado', max_length=30, verbose_name='Nombre cliente'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(default='Nombre usuario', max_length=30),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(default='password usuario', max_length=15),
        ),
    ]
