# Generated by Django 4.1.4 on 2023-02-25 01:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0017_alter_cliente_cli_apellido_alter_cliente_cli_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cli_email',
            field=models.EmailField(default='Email cliente', max_length=30, primary_key=True, serialize=False, validators=[django.core.validators.EmailValidator(message='Correo electrónico inválido')], verbose_name='Email cliente'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cli_password',
            field=models.CharField(default='Contraseña cliente', max_length=32, verbose_name='Contraseña'),
        ),
        migrations.AlterField(
            model_name='personal_tienda',
            name='per_apellido',
            field=models.CharField(default='Apellido empleado', max_length=30, verbose_name='Apellido empleado'),
        ),
        migrations.AlterField(
            model_name='personal_tienda',
            name='per_email',
            field=models.EmailField(default='Email empleado', max_length=30, primary_key=True, serialize=False, validators=[django.core.validators.EmailValidator(message='Correo electrónico inválido')], verbose_name='Email empleado'),
        ),
        migrations.AlterField(
            model_name='personal_tienda',
            name='per_nombre',
            field=models.CharField(default='Nombre empleado', max_length=30, verbose_name='Nombre empleado'),
        ),
        migrations.AlterField(
            model_name='personal_tienda',
            name='per_password',
            field=models.CharField(default='Contraseña empleado', max_length=32, verbose_name='Contraseña'),
        ),
    ]
