# Generated by Django 4.1.4 on 2023-02-25 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0018_alter_cliente_cli_email_alter_cliente_cli_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_categoria',
            name='cat_nombre',
            field=models.CharField(choices=[(1, 'Alimento perro'), (2, 'Alimento gato'), (3, 'Juguetes perros'), (4, 'Juguetes gatos')], default='test', max_length=10),
        ),
    ]
