# Generated by Django 4.1.4 on 2023-02-25 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0019_test_categoria_cat_nombre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test_categoria',
        ),
    ]
